title = "SmartWatcher"
baseURL = "https://as4mo3.github.io/SmartWatcher/"
languageCode = "en-us"
theme = "airspace-hugo"
publishDir = "docs"


[menu]

  # [[menu.header]]
  #   weight = 6
  #   name = "Form"
  #   url = "/form"
#  [[menu.header]]
#    weight = 3
#    name = "Other"
#    url = "/blog"


# The site's parameters
[params]

  # If you want to remove the copyright text you need a Themefisher license.
  # This license is offered with a 50% discount for all Hugo users.
  # For information see https://github.com/gohugoio/hugoThemes/issues/260

  dateFormat = "6 January 2006"

  home = "Home"

  [params.slider]
    enable = true
    title = "Propelling Voice Activated Commands into the Artifical Intelligence era"
    subtitle = "This Amazon Alexa Skill learn from your actions, and then does them for you. Leaving you more free time every day."

  [params.wrapper]
    enable = true
    title = "Mission Statement"
    # italic = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics"
   paragraph = "In order to best more forward into a truly hands-free and fully automated future, we have to start with small actions: such as turning the lights on and off. This Amazon Alexa skill integrates with your smart home devices, and learns when you do certain actions. Over time, this skill will become so good at its task that you won't even have to say, 'Alexa, turn off the lights'."

  [params.blog]
    enable = true
    title = "Misson Statement"
    subtitle = "Catch up with us, anytime and anywhere"
    paragraph = "Transforming the way that clinicians diagnose headaches by empowering patients to share their headache symptoms in real time. Then, by analyzing headache patterns, and following the clinical outcomes associated with each pattern, our algorithm will learn to recognize if a patient’s headache pattern indicates that they are high or low risk. Our program will improve patient outcomes, reduce radiation exposure, and decrease medical costs."

#  [params.blog]
#    enable = true
#    title = "Get The Latest On What We're doing"
#    subtitle = "Catch up with us, anytime and anywhere"


  [params.feature]
    enable = true
    title = "SmartWatcher Code Flow"
    # content = "testing content"

  [params.call]
    enable = false
    title = "Inspiration"
    paragraph = "It all started with two challenges we saw in the clinical space: 1. Clinicians needed information from patients about their headaches in order to understand what was causing them, and sometimes used paper headache journals 2. About a billion dollars are spent per year on headache related neuroimaging, however only a small percentage of scans show up clinically relevant findings."

  [params.contact]
    enable = true
    title = "Drop us a note"
    subtitle = "Don’t just take our word for it. Check out some of our latest work."
    [params.contact.form]
      name = "Your name"
      email = "Your email"
      subject = "Your subject"
      message = "Your message"
      button = "Send message"
    [params.contact.box]
      title = "Stop by for a visit"
      address = "North Main Street, Brooklyn Australia"
      email = "Email: contact@mail.com"
      phone = "Phone: +88 01672 506 744"
    [params.contact.gmaps]
      title = "We Also Count in Google Maps"

  [params.form]
    [[params.form.numInput]]
      name = "How old are you?"
    [[params.form.numInput]]
      name = "How many times per year do you get headaches?"
    [[params.form.numInput]]
      name = "What is the intensity of your headache, out of 10?"
    [[params.form.numInput]]
      name = "Please list any medications that you are taking."
    [[params.form.radio]]
        name = "What is your sex?"
      [[params.form.radio.buttons]]
        button = "Female"
        name = "sex"
      [[params.form.radio.buttons]]
        button = "Male"
        name = "sex"
    [[params.form.radio]]
      name = "What is your race?"
      [[params.form.radio.buttons]]
        button = "African American"
        name = "race"
      [[params.form.radio.buttons]]
        button = "Asian"
        name = "race"
      [[params.form.radio.buttons]]
        button = "Native American or Other Pasific Islander"
        name = "race"
      [[params.form.radio.buttons]]
        button = "Hispanic or Latino"
        name = "race"
      [[params.form.radio.buttons]]
        button = "White or Caucasian"
        name = "race"
    [[params.form.radio]]
      name = "How fast is the onset of your pain?"
      [[params.form.radio.buttons]]
        button = "Less than 1 minute"
        name = "onset"
      [[params.form.radio.buttons]]
        button = "Between 1 minute and 5 minutes"
        name = "onset"
      [[params.form.radio.buttons]]
        button = "More than 5 minutes"
        name = "onset"
    [[params.form.radio]]
      name = "Where is the location of your pain?"
      [[params.form.radio.buttons]]
        button = "Left side of head"
        name = "pain"
      [[params.form.radio.buttons]]
        button = "Right side of head"
        name = "pain"
      [[params.form.radio.buttons]]
        button = "Front of head"
        name = "pain"
      [[params.form.radio.buttons]]
        button = "Back of head"
        name = "pain"
      [[params.form.radio.buttons]]
        button = "Entire head"
        name = "pain"
    [[params.form.checkboxes]]
      yes = "yes"
      no = "no"
      [[params.form.checkboxes.names]]
        name = "primary"
        testing = "testing"
      [[params.form.checkboxes.names]]
        name = "aura"
        testing = "testing"
      [[params.form.checkboxes.names]]
        name = "ringing"
        testing = "testing"
      [[params.form.checkboxes.names]]
        name = "visionBlurry"
        testing = "testing"
      [[params.form.checkboxes.names]]
        name = "visionLossComplete"
        testing = "testing"
      [[params.form.checkboxes.names]]
        name = "droopingFace"
        testing = "testing"
      [[params.form.checkboxes.names]]
        name = "neckPain"
        testing = "testing"
      [[params.form.checkboxes.names]]
        name = "lossOfSmell"
        testing = "testing"
      [[params.form.checkboxes.names]]
        name = "lessOfTaste"
        testing = "testing"
      [[params.form.checkboxes.names]]
        name = "seizure"
        testing = "testing"
      [[params.form.checkboxes.names]]
        name = "nouseaOrVomiting"
        testing = "testing"
      [[params.form.checkboxes.names]]
        name = "lightTrigger"
        testing = "testing"
      [[params.form.checkboxes.names]]
        name = "loudNoiseTrigger"
        testing = "testing"
      [[params.form.checkboxes.names]]
        name = "allergenTrigger"
        testing = "testing"
      [[params.form.checkboxes.names]]
        name = "dehydrationTrigger"
        testing = "testing"
      [[params.form.checkboxes.names]]
        name = "bendingOverTrigger"
        testing = "testing"
      [[params.form.checkboxes.names]]
        name = "stressTrigger"
        testing = "testing"
      [[params.form.checkboxes.names]]
        name = "periodTrigger"
        testing = "testing"
      [[params.form.checkboxes.names]]
        name = "exerciseTrigger"
        testing = "testing"
      [[params.form.checkboxes.names]]
        name = "sleepPatternChanTrigger"
        testing = "testing"
      [[params.form.checkboxes.names]]
        name = "chemicalTrigger"
        testing = "testing"
      [[params.form.checkboxes.names]]
        name = "alcoholTrigger"
        testing = "testing"
      [[params.form.checkboxes.names]]
        name = "caffeineTrigger"
        testing = "testing"
      [[params.form.checkboxes.names]]
        name = "restingAlleviator"
        testing = "testing"
      [[params.form.checkboxes.names]]
        name = "waterAlleviator"
        testing = "testing"
      [[params.form.checkboxes.names]]
        name = "darkRoomAlleviator"
        testing = "testing"
      [[params.form.checkboxes.names]]
        name = "silenceAlleviator"
        testing = "testing"
